backend = "glx";
vsync = true;

glx-no-stencil = true;
use-damage = true;

fading = false;

detect-client-opacity = true;
detect-rounded-corners = true;
detect-transient = true;

unredir-if-possible = true;

wintypes:
{
  tooltip      = { fade = false; shadow = false; focus = true; };
  dock         = { shadow = false; };
  dnd          = { shadow = false; };
  popup_menu   = { shadow = false; };
  dropdown_menu = { shadow = false; };
};
